// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    3DText: typeof import('./src/components/basic/3DText.vue')['default']
    Animation: typeof import('./src/components/basic/Animation.vue')['default']
    Basic: typeof import('./src/components/basic/index.vue')['default']
    Camera: typeof import('./src/components/basic/Camera.vue')['default']
    copy: typeof import('./src/components/basic/Fullscreen copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FirstScene: typeof import('./src/components/basic/FirstScene.vue')['default']
    Fullscence: typeof import('./src/components/basic/Fullscence.vue')['default']
    Fullscreen: typeof import('./src/components/basic/Fullscreen.vue')['default']
    Geometry: typeof import('./src/components/basic/Geometry.vue')['default']
    Geometryy: typeof import('./src/components/basic/Geometryy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Lights: typeof import('./src/components/basic/Lights.vue')['default']
    'Lights.': typeof import('./src/components/basic/Lights..vue')['default']
    'Linghts.': typeof import('./src/components/basic/Linghts..vue')['default']
    Materials: typeof import('./src/components/basic/Materials.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textrues: typeof import('./src/components/basic/Textrues.vue')['default']
    Textures: typeof import('./src/components/basic/Textures.vue')['default']
    Transform: typeof import('./src/components/basic/Transform.vue')['default']
    Transforms: typeof import('./src/components/basic/Transforms.vue')['default']
  }
}
