// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedGalaxy: typeof import('./src/three/basic/AnimatedGalaxy.vue')['default']
    Animation: typeof import('./src/three/basic/Animation.vue')['default']
    Camera: typeof import('./src/three/basic/Camera.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FirstScene: typeof import('./src/three/basic/FirstScene.vue')['default']
    Fullscreen: typeof import('./src/three/basic/Fullscreen.vue')['default']
    Galaxy: typeof import('./src/three/basic/Galaxy.vue')['default']
    Geometry: typeof import('./src/three/basic/Geometry.vue')['default']
    HelloWorld: typeof import('./src/three/HelloWorld.vue')['default']
    House: typeof import('./src/projects/House.vue')['default']
    Lights: typeof import('./src/three/basic/Lights.vue')['default']
    Materials: typeof import('./src/three/basic/Materials.vue')['default']
    Models: typeof import('./src/three/basic/Models.vue')['default']
    ModifiedMaterial: typeof import('./src/three/basic/ModifiedMaterial.vue')['default']
    Particles: typeof import('./src/three/basic/Particles.vue')['default']
    Physics: typeof import('./src/three/basic/Physics.vue')['default']
    PostProcessing: typeof import('./src/three/basic/PostProcessing.vue')['default']
    RagingSea: typeof import('./src/three/basic/RagingSea.vue')['default']
    RayCaster: typeof import('./src/three/basic/RayCaster.vue')['default']
    Realistic: typeof import('./src/three/basic/Realistic.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBaseAnimation: typeof import('./src/three/basic/ScrollBaseAnimation.vue')['default']
    ShaderPatterns: typeof import('./src/three/basic/ShaderPatterns.vue')['default']
    Shaders: typeof import('./src/three/basic/Shaders.vue')['default']
    Shadow: typeof import('./src/three/basic/Shadow.vue')['default']
    Textures: typeof import('./src/three/basic/Textures.vue')['default']
    ThreeDText: typeof import('./src/three/basic/ThreeDText.vue')['default']
    Transform: typeof import('./src/three/basic/Transform.vue')['default']
  }
}
